#!/usr/bin/bash

set ${SET_X:+-x} -eou pipefail

trap '[[ $BASH_COMMAND != echo* ]] && [[ $BASH_COMMAND != log* ]] && echo "+ $BASH_COMMAND"' DEBUG

log() {
  echo "=== $* ==="
}

log "Setting up Nix for immutable/atomic OS"

# ============================================
# 1. Download the Determinate Nix installer
# ============================================
mkdir -p /usr/libexec
curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix -o /usr/libexec/nix-installer && \
    chmod a+rx /usr/libexec/nix-installer

log "Nix installer downloaded to /usr/libexec/nix-installer"

# ============================================
# 2. Create /nix symlink to /var/nix
# ============================================
# This symlink becomes part of the immutable image, pointing to writable /var/nix
log "Creating /nix -> /var/nix symlink (baked into image)"
ln -sf /var/nix /nix

# ============================================
# 3. Create nixbld group and build users
# ============================================
log "Creating nixbld group and build users"

NIX_BUILD_GROUP_ID=30000
NIX_BUILD_GROUP_NAME=nixbld
NIX_BUILD_USER_ID_BASE=30000
NIX_BUILD_USER_COUNT=32
NIX_BUILD_USER_PREFIX=nixbld

# Create the nixbld group
if ! getent group "${NIX_BUILD_GROUP_NAME}" > /dev/null 2>&1; then
    groupadd -g "${NIX_BUILD_GROUP_ID}" "${NIX_BUILD_GROUP_NAME}"
    log "Created group ${NIX_BUILD_GROUP_NAME} with GID ${NIX_BUILD_GROUP_ID}"
fi

# Create the nixbld users
for i in $(seq 0 $((NIX_BUILD_USER_COUNT - 1))); do
    USER_NAME="${NIX_BUILD_USER_PREFIX}${i}"
    USER_ID=$((NIX_BUILD_USER_ID_BASE + i))
    
    if ! id "${USER_NAME}" > /dev/null 2>&1; then
        useradd \
            --home-dir /var/empty \
            --comment "Nix build user ${i}" \
            --gid "${NIX_BUILD_GROUP_ID}" \
            --groups "${NIX_BUILD_GROUP_NAME}" \
            --no-create-home \
            --no-user-group \
            --shell /sbin/nologin \
            --uid "${USER_ID}" \
            --system \
            "${USER_NAME}"
    fi
done

log "Created ${NIX_BUILD_USER_COUNT} nixbld users"

# ============================================
# 4. Create Nix configuration
# ============================================
log "Creating Nix configuration"

mkdir -p /etc/nix
cat > /etc/nix/nix.conf << 'EOF'
# Generated by BlueBuild for Determinate Nix
build-users-group = nixbld
experimental-features = nix-command flakes
bash-prompt-prefix = (nix:$name)\040
max-jobs = auto
extra-nix-path = nixpkgs=flake:nixpkgs
upgrade-nix-store-path-url = https://install.determinate.systems/nix-upgrade/stable/universal
EOF

log "Created /etc/nix/nix.conf"

# ============================================
# 5. Create systemd service files
# ============================================
log "Creating systemd service files for nix-daemon"

# nix-daemon.service
cat > /usr/lib/systemd/system/nix-daemon.service << 'EOF'
[Unit]
Description=Nix Daemon
Documentation=man:nix-daemon https://docs.determinate.systems
RequiresMountsFor=/nix/store
RequiresMountsFor=/nix/var
ConditionPathIsReadWrite=/nix/var/nix/daemon-socket

[Service]
ExecStart=/nix/var/nix/profiles/default/bin/nix daemon
KillMode=process
LimitNOFILE=1048576
TasksMax=infinity

[Install]
WantedBy=multi-user.target
EOF

# nix-daemon.socket
cat > /usr/lib/systemd/system/nix-daemon.socket << 'EOF'
[Unit]
Description=Nix Daemon Socket
Documentation=man:nix-daemon https://docs.determinate.systems
RequiresMountsFor=/nix/store
RequiresMountsFor=/nix/var
ConditionPathIsReadWrite=/nix/var/nix/daemon-socket

[Socket]
ListenStream=/nix/var/nix/daemon-socket/socket

[Install]
WantedBy=sockets.target
EOF

log "Created nix-daemon.service and nix-daemon.socket"

# ============================================
# 6. Create shell profile scripts
# ============================================
log "Creating shell profile scripts"

mkdir -p /etc/profile.d

cat > /etc/profile.d/nix.sh << 'EOF'
# Nix profile script
if [ -e '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh' ]; then
    . '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh'
fi
EOF

cat > /etc/bash.bashrc.d/nix.sh << 'EOF' 2>/dev/null || mkdir -p /etc/bash.bashrc.d && cat > /etc/bash.bashrc.d/nix.sh << 'EOF'
# Nix bash configuration
if [ -e '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh' ]; then
    . '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh'
fi
EOF

# Fish shell support
mkdir -p /etc/fish/conf.d
cat > /etc/fish/conf.d/nix.fish << 'EOF'
# Nix fish configuration  
if test -e '/nix/var/nix/profiles/default/etc/fish/conf.d/nix-daemon.fish'
    source '/nix/var/nix/profiles/default/etc/fish/conf.d/nix-daemon.fish'
end
EOF

log "Created shell profile scripts"

# ============================================
# 7. Set up tmpfiles.d for runtime directories
# ============================================
log "tmpfiles.d will create /var/nix at boot"

log "========================================"
log "Nix pre-configuration complete!"
log "After booting, run: just install-nix"
log "========================================"
